# version: '3.8'  # Obsoleto no Compose V2

services:
  integration-service:
    build: .
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
      - KAFKA_BROKERS=kafka:9092
      - MONGODB_URI=mongodb://mongodb:27017/integration
    volumes:
      - ./src:/app/src
    depends_on:
      kafka
        condition: service_started
      mongodb:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully
    networks:
      - hospital-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - hospital-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - hospital-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27018:27017"  # Porta externa 27018 para evitar conflito
    volumes:
      - mongo-data:/data/db
    networks:
      - hospital-network

  kafka-init:
    build: .
    command: npm run topics:create
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
    networks:
      - hospital-network
    restart: "no"

  mock-lab:
    build: ./mocks/mock-lab
    ports:
      - "4001:4001"
    depends_on:
      - integration-service
    networks:
      - hospital-network

volumes:
  mongo-data:

networks:
  hospital-network:
    driver: bridge